python demo.py \
  --opt Adam \
  --loss_fn loss2 \
  --lr 1e-2 \
  --epochs 200 \
  --beta1 0.81 \
  --beta2 0.8\
  --r_min -10 \
  --r_max 10 \
  --init_x 5 \
  --init_y 5 \
  --out_dir "./imgs/tune_adam"